name: 'Terraform-Destroy-Flow'

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform_destroy:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      run: terraform init -reconfigure

    - name: Show Terraform State (Debug)
      run: terraform state list || echo "No resources tracked by Terraform."

    - name: Terraform Destroy
      run: terraform destroy -auto-approve -input=false
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

    - name: Manually Remove Orphaned State (if needed)
      if: failure()
      run: terraform state rm $(terraform state list) || echo "No state found."
