name: 'Terraform-Destroy-Flow'

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform_destroy:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init with Remote Backend
      run: terraform init -reconfigure || echo "Reinitialization failed!"

    - name: Show Terraform State (Debug)
      run: terraform state list || echo "No resources tracked by Terraform."

    - name: Import Resources (If Needed)
      run: |
        terraform import google_compute_instance.my_instance projects/YOUR_PROJECT_ID/zones/YOUR_ZONE/instances/YOUR_INSTANCE_NAME || echo "Import failed, resource might not exist."

    - name: Terraform Destroy
      run: terraform destroy -auto-approve -input=false || echo "Destroy failed!"
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
