name: 'GCP-Infra-flow'

on:
  workflow_dispatch:  # Allows manual trigger for destroy

permissions:
  contents: read

jobs:
  terraform_destroy:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      run: terraform init

    - name: Show Terraform State (Debug)
      run: terraform state list || echo "No resources found."

    - name: Terraform Destroy
      run: terraform destroy -auto-approve -input=false
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
